# Generated by Django 2.2.1 on 2019-06-07 15:25

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_tag_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_color',
            field=colorfield.fields.ColorField(default='#adb5bd', max_length=18),
        ),
    ]
