# Generated by Django 2.2.2 on 2019-06-10 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_auto_20190607_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='icon',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
