# Generated by Django 2.2.2 on 2019-06-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0005_auto_20190611_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='icon',
            field=models.URLField(default='https://cdn0.iconfinder.com/data/icons/heroicons-ui/24/icon-hashtag-512.png', max_length=255),
        ),
    ]
