# Generated by Django 2.2.2 on 2019-06-11 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_blog_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['updated_at']},
        ),
    ]
