# Generated by Django 2.2.2 on 2019-06-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20190611_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author_contact',
            field=models.TextField(default='https://www.google.com'),
        ),
    ]
