# Generated by Django 2.2.2 on 2019-06-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_blog_author_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author_contact',
            field=models.TextField(blank=True, default='https://www.google.com'),
        ),
    ]
