# Generated by Django 2.2.1 on 2019-05-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0004_auto_20190530_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
