# Generated by Django 2.2.2 on 2019-06-11 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0005_podcast_show'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='podcast',
            options={'ordering': ['created_at']},
        ),
    ]
