# Generated by Django 2.2.2 on 2019-06-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0006_auto_20190611_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='author',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='podcast',
            name='author_contact',
            field=models.TextField(default='https://www.google.com'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
