# Generated by Django 2.2.2 on 2019-06-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0007_auto_20190612_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='author_contact',
            field=models.TextField(blank=True, default='https://www.google.com'),
        ),
    ]
